language: node_js
node_js:
- '0.10'
env:
  matrix:
  - JOB=unit
  - JOB=e2e BROWSER=chrome
  - JOB=e2e BROWSER=firefox
  global:
  - LOGS_DIR: /tmp/sauce-build/logs
  - BROWSER_PROVIDER_READY_FILE: /tmp/sauce-connect-ready
  - secure: bT+mOdqtwJJlj34zaljgzpcsxtEnamFSNDI0KEBXutj3rCwtMGVX2AGrfYSbMm+95BpL7AMzT1V8FgHTSdXKLqirToXwrT+EN5EQXid5fXK2RYMD9SVo8EmlFP7T4ux37M2eSccs7bIIwD/9CSYa30nbRB4XawWt0YtdtuxTXhw=
  - secure: FmR5fmv2ljTdxbthTPwohxw2GiDLGqjCUhc4w7/pegakzJ+p+8F/zDsg9XcWE38N1UXcHNTjTzoh5HtptbEQMiHF7INXECObSwTJPdh7Trcq0KtxxcUWqo3wwv6st+2JnyPEf2BoQFXycfsA/djUw12qcXDwl422EttWbkoVS/Q=
before_script:
- mkdir -p $LOGS_DIR
- ./misc/sauce/sauce_connect_setup.sh
- npm install -g bower grunt-cli
- bower install
- ./misc/travis/wait_for_ready_file.sh
script:
- ./misc/travis/run.sh
